#APP = main
#
#APP_SRCS := $(wildcard src/*.c) 
#
#ifndef CORE
#CORE=1
#else
#CORE= $(CORE)
#endif
#
#APP_CFLAGS += -DNUM_CORES=$(CORE) -DGAP_SDK=1 -IDORY_network/inc -O3 -w -fno-tree-loop-distribute-patterns
#APP_LDFLAGS += -lm
#
#PLPBRIDGE_FLAGS += -f
#
#include $(RULES_DIR)/pmsis_rules.mk
