################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJDUMP_LIST := 
C_UPPER_DEPS := 
S_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Drivers/BSP/Components/exc7200 \
Drivers/BSP/Components/ft5336 \
Drivers/BSP/Components/mfxstm32l152 \
Drivers/BSP/Components/ov9655 \
Drivers/BSP/Components/s5k5cag \
Drivers/BSP/Components/stmpe811 \
Drivers/BSP/Components/ts3510 \
Drivers/BSP/Components/wm8994 \
Drivers/BSP/STM32746G-Discovery \
Drivers/STM32F7xx_HAL_Driver/Src \
Src/ViT_00/config/startup \
Src/ViT_00/config \
Src/ViT_00/libs/CMSIS/DSP/Source/BasicMathFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/BayesFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/CommonTables \
Src/ViT_00/libs/CMSIS/DSP/Source/ComplexMathFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/ControllerFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/FastMathFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/FilteringFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/MatrixFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/SVMFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/SupportFunctions \
Src/ViT_00/libs/CMSIS/DSP/Source/TransformFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/ActivationFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/BasicMathFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/ConcatenationFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/ConvolutionFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/FullyConnectedFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/NNSupportFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/PoolingFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/ReshapeFunctions \
Src/ViT_00/libs/CMSIS/NN/Source/SoftmaxFunctions \
Src/ViT_00/libs/STM32F7xx_HAL_Driver/Src/Legacy \
Src/ViT_00/libs/STM32F7xx_HAL_Driver/Src \
Src/ViT_00/libs/freertos/FreeRTOS/Source \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/GCC/ARM_CM23 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/GCC/ARM_CM23_NTZ \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/GCC/ARM_CM33 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/IAR/ARM_CM23 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/IAR/ARM_CM23_NTZ \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/IAR/ARM_CM33 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/IAR/ARM_CM33_NTZ \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/secure/context/portable/GCC/ARM_CM23 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/secure/context/portable/GCC/ARM_CM33 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/secure/context/portable/IAR/ARM_CM23 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/secure/context/portable/IAR/ARM_CM33 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/secure/context \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/secure/heap \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ARMv8M/secure/init \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/BCC/16BitDOS/Flsh186 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/BCC/16BitDOS/PC \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/BCC/16BitDOS/common \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/CCS/ARM_CM3 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/CCS/ARM_CM4F \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/CCS/ARM_Cortex-R4 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/CCS/MSP430X \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/CodeWarrior/ColdFire_V1 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/CodeWarrior/ColdFire_V2 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/CodeWarrior/HCS12 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Common \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM7_AT91FR40008 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM7_AT91SAM7S \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM7_LPC2000 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM7_LPC23xx \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CA53_64_BIT \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CA9 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM0 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM23/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM23/secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM23_NTZ/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM3 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM33/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM33/secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM33_NTZ/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM3_MPU \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM4F \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM4_MPU \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CR5 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ARM_CRx_No_GIC \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ATMega323 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/AVR32_UC3 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/CORTUS_APS3 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/ColdFire_V2 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/H8S2329 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/HCS12 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/IA32_flat \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/MCF5235 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/MSP430F449 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/MicroBlaze \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/MicroBlazeV8 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/MicroBlazeV9 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/NiosII \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/PPC405_Xilinx \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/PPC440_Xilinx \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/RISC-V \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/RL78 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/RX100 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/RX600 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/RX600v2 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/STR75x \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/GCC/TriCore_1782 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/78K0R \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CA5_No_GIC \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CA9 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM0 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM23/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM23/secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM23_NTZ/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM3 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM33/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM33/secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM33_NTZ/non_secure \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM4F \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM4F_MPU \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CM7/r0p1 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ARM_CRx_No_GIC \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/ATMega323 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/AVR32_UC3 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/AtmelSAM7S64 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/AtmelSAM9XE \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/LPC2000 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/MSP430 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/MSP430X \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/RL78 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/RX100 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/RX600 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/RXv2 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/STR71x \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/STR75x \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/STR91x \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/IAR/V850ES \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/MPLAB/PIC18F \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/MPLAB/PIC24_dsPIC \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/MPLAB/PIC32MEC14xx \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/MPLAB/PIC32MX \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/MPLAB/PIC32MZ \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/MSVC-MingW \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/MemMang \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/MikroC/ARM_CM4F \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Paradigm/Tern_EE/large_untested \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Paradigm/Tern_EE/small \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/RVDS/ARM7_LPC21xx \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/RVDS/ARM_CA9 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/RVDS/ARM_CM0 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/RVDS/ARM_CM3 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/RVDS/ARM_CM4F \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/RVDS/ARM_CM4_MPU \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/RVDS/ARM_CM7/r0p1 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Renesas/RX100 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Renesas/RX200 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Renesas/RX600 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Renesas/RX600v2 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Renesas/SH2A_FPU \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Rowley/MSP430F449 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/SDCC/Cygnal \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Softune/MB91460 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Softune/MB96340 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/Tasking/ARM_CM4F \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ThirdParty/GCC/RISC-V \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/ThirdParty/XCC/Xtensa \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/WizC/PIC18/Drivers/Tick \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/WizC/PIC18 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/oWatcom/16BitDOS/Flsh186 \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/oWatcom/16BitDOS/PC \
Src/ViT_00/libs/freertos/FreeRTOS/Source/portable/oWatcom/16BitDOS/common \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/Demo_IP_Protocols/Common \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/Demo_IP_Protocols/FTP \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/Demo_IP_Protocols/HTTP \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/Demo_IP_Protocols/NTP \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/FreeRTOS_Plus_CLI_Demos \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/FreeRTOS_Plus_FAT_SL_Demos/CreateExampleFiles \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/FreeRTOS_Plus_UDP_Demos/CLICommands \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/FreeRTOS_Plus_UDP_Demos/EchoClients \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/Common/FreeRTOS_Plus_UDP_Demos/TraceMacros/Example1 \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/FreeRTOS_Plus_CLI_with_Trace_Windows_Simulator \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/FreeRTOS_Plus_Reliance_Edge_and_CLI_Windows_Simulator/ConfigurationFiles \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/FreeRTOS_Plus_Reliance_Edge_and_CLI_Windows_Simulator \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/FreeRTOS_Plus_TCP_Minimal_Windows_Simulator/DemoTasks \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/FreeRTOS_Plus_TCP_Minimal_Windows_Simulator/WinPCap \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/FreeRTOS_Plus_TCP_Minimal_Windows_Simulator \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Demo/FreeRTOS_Plus_WolfSSL_Windows_Simulator \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-CLI \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/BufferManagement \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/ATSAM4E \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/Common \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/LPC17xx \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/LPC18xx \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/SH2A \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/STM32F7xx \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/STM32Fxx \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/WinPCap \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/Zynq \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/ksz8851snl \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-Trace/streamports/ARM_ITM \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-Trace/streamports/File \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-Trace/streamports/Jlink_RTT \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-Trace/streamports/TCPIP \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-Trace/streamports/USB_CDC \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/FreeRTOS-Plus-Trace \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/fse \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/os/freertos/services \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/posix \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/tests/posix \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/tests/util \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/toolcmn \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/util \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/examples/client \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/examples/echoclient \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/examples/echoserver \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/examples/server \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/src \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/sslSniffer/sslSnifferTest \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/swig \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/tests \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/testsuite \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/benchmark \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/port/pic32 \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/port/ti \
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/test \
Src/ViT_00/libs/noarch_c_lib \
Src/ViT_00 \
Src/ViT_00/src \
Src/flatbuffers/src \
Src \
Src/sys \
Src/tensorflow/ruy/profiler \
Src/tensorflow/tensorflow/lite/c \
Src/tensorflow/tensorflow/lite/core/api \
Src/tensorflow/tensorflow/lite/core \
Src/tensorflow/tensorflow/lite/flatbuffers/src \
Src/tensorflow/tensorflow/lite/kernels/internal/optimized \
Src/tensorflow/tensorflow/lite/kernels/internal \
Src/tensorflow/tensorflow/lite/kernels/internal/reference \
Src/tensorflow/tensorflow/lite/kernels \
Src/tensorflow/tensorflow/lite/micro \
Src/tensorflow/tensorflow/lite/micro/kernels \
Src/tensorflow/tensorflow/lite/micro/kernels/cmsis-nn \
Src/tensorflow/tensorflow/lite/micro/memory_planner \
Src/tensorflow/tensorflow/lite/micro/testing \
Utilities/Fonts \

