################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
S_SRCS += \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes_asm.s 

C_SRCS += \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/arc4.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asm.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asn.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/blake2b.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/camellia.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha20_poly1305.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/coding.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/compress.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/curve25519.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/des3.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dh.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dsa.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc_fp.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ed25519.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/error.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_low_mem.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_operations.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_low_mem.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_operations.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hash.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hc128.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hmac.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/integer.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/logging.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md2.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md4.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md5.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/memory.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/misc.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pkcs7.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/poly1305.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pwdbased.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rabbit.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/random.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ripemd.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rsa.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha256.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha512.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/tfm.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/wc_port.c 

S_DEPS += \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes_asm.d 

C_DEPS += \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/arc4.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asm.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asn.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/blake2b.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/camellia.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha20_poly1305.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/coding.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/compress.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/curve25519.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/des3.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dh.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dsa.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc_fp.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ed25519.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/error.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_low_mem.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_operations.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_low_mem.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_operations.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hash.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hc128.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hmac.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/integer.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/logging.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md2.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md4.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md5.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/memory.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/misc.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pkcs7.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/poly1305.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pwdbased.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rabbit.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/random.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ripemd.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rsa.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha256.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha512.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/tfm.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/wc_port.d 

OBJS += \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes_asm.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/arc4.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asm.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asn.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/blake2b.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/camellia.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha20_poly1305.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/coding.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/compress.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/curve25519.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/des3.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dh.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dsa.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc_fp.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ed25519.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/error.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_low_mem.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_operations.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_low_mem.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_operations.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hash.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hc128.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hmac.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/integer.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/logging.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md2.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md4.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md5.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/memory.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/misc.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pkcs7.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/poly1305.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pwdbased.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rabbit.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/random.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ripemd.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rsa.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha256.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha512.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/tfm.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/wc_port.o 


# Each subdirectory must supply rules for building sources it contributes
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes_asm.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes_asm.s
	arm-none-eabi-gcc -mcpu=cortex-m7 -g3 -DSTM32F746xx -c -IC:/Users/ASW-MNO-Admin/Atollic/TrueSTUDIO/ARM_videos/STM32F746G-Discovery/src -IC:/Users/ASW-MNO-Admin/Atollic/TrueSTUDIO/ARM_videos/STM32F746G-Discovery/Drivers/CMSIS/Include -IC:/Users/ASW-MNO-Admin/Atollic/TrueSTUDIO/ARM_videos/STM32F746G-Discovery/Drivers/CMSIS/Device/ST/STM32F7xx/Include -IC:/Users/ASW-MNO-Admin/Atollic/TrueSTUDIO/ARM_videos/STM32F746G-Discovery/Drivers/STM32F7xx_HAL_Driver/Inc -x assembler-with-cpp -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/aes_asm.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@" "$<"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/arc4.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/arc4.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/arc4.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asm.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asm.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asm.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asn.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asn.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/asn.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/blake2b.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/blake2b.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/blake2b.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/camellia.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/camellia.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/camellia.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha20_poly1305.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha20_poly1305.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/chacha20_poly1305.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/coding.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/coding.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/coding.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/compress.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/compress.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/compress.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/curve25519.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/curve25519.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/curve25519.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/des3.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/des3.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/des3.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dh.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dh.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dh.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dsa.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dsa.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/dsa.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc_fp.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc_fp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ecc_fp.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ed25519.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ed25519.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ed25519.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/error.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/error.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/error.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_low_mem.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_low_mem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_low_mem.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_operations.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_operations.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/fe_operations.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_low_mem.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_low_mem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_low_mem.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_operations.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_operations.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ge_operations.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hash.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hash.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hc128.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hc128.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hc128.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hmac.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hmac.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/hmac.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/integer.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/integer.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/integer.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/logging.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/logging.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/logging.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md2.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md2.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md2.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md4.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md4.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md4.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md5.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md5.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/md5.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/memory.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/memory.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/memory.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/misc.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/misc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/misc.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pkcs7.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pkcs7.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pkcs7.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/poly1305.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/poly1305.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/poly1305.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pwdbased.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pwdbased.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/pwdbased.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rabbit.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rabbit.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rabbit.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/random.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/random.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/random.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ripemd.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ripemd.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/ripemd.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rsa.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rsa.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/rsa.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha256.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha256.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha512.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha512.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/sha512.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/tfm.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/tfm.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/tfm.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/wc_port.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/wc_port.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/wolfcrypt/src/wc_port.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

