################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/aes.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/des3.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips_test.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/hmac.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/misc.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/random.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/rsa.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha256.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha512.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_first.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_last.c 

C_DEPS += \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/aes.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/des3.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips_test.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/hmac.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/misc.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/random.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/rsa.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha256.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha512.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_first.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_last.d 

OBJS += \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/aes.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/des3.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips_test.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/hmac.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/misc.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/random.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/rsa.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha256.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha512.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_first.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_last.o 


# Each subdirectory must supply rules for building sources it contributes
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/aes.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/aes.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/aes.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/des3.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/des3.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/des3.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips_test.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips_test.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/fips_test.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/hmac.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/hmac.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/hmac.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/misc.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/misc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/misc.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/random.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/random.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/random.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/rsa.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/rsa.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/rsa.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha256.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha256.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha512.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha512.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/sha512.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_first.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_first.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_first.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_last.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_last.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/WolfSSL/ctaocrypt/src/wolfcrypt_last.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

