################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c 

C_DEPS += \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o 


# Each subdirectory must supply rules for building sources it contributes
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_entropy_f64.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_kullback_leibler_f64.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_logsumexp_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_no_idx_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q15.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q31.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_max_q7.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q15.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q31.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_mean_q7.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q15.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q31.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_min_q7.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q15.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q31.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_power_q7.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q15.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_rms_q31.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q15.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_std_q31.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q15.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/StatisticsFunctions/arm_var_q31.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

