from .add import parse_add
from .avgpool import parse_avgpool
from .conv2d import parse_conv2d
from .fc import parse_fc
from .maxpool import parse_maxpool
from .mean1dto2d import parse_mead1dto2d
from .SEelement import parse_SEelement
from .upsample import parse_upsample
from .gather import parse_gather
from .shape import parse_shape
from .strided_slice import parse_strided_slice
from .pack import parse_pack
from .tile import parse_tile
from .concatenation import parse_concatenation
from .squared_difference import parse_squared_difference
from .rsqrt import parse_rsqrt
from .mul import parse_mul
from .sub import parse_sub
from .reduce_prod import parse_reduce_prod
from .fusion_operator import parse_fusion
from .fully_connected import parse_fully_connected
from .batch_matmul import parse_batch_matmul
from .softmax import parse_softmax
from .placeholder_for_greater_op_codes import parse_placeholder_for_greater_op_codes