from .add import parse_add
from .avgpool import parse_avgpool
from .batchmatmul import parse_batchmatmul
from .cast import parse_cast
from .conv2d import parse_conv2d
from .div import parse_div
from .equal import parse_equal
from .fc import parse_fc
from .maxpool import parse_maxpool
from .mean1dto2d import parse_mead1dto2d
from .mul import parse_mul
from .notequal import parse_notequal
from .reshape import parse_reshape_fuse_tensor_tuple
from .rsqrt import parse_rsqrt
from .SEelement import parse_SEelement
from .slice import parse_slice
from .softmax import parse_softmax
from .squarddiff import parse_squarddiff
from .sub import parse_sub
from .upsample import parse_upsample
