################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctions.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_boolean_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_braycurtis_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_canberra_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_chebyshev_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cityblock_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_correlation_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cosine_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_dice_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_euclidean_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_hamming_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jaccard_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jensenshannon_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_kulsinski_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_minkowski_distance_f32.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_rogerstanimoto_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_russellrao_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalmichener_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalsneath_distance.c \
../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_yule_distance.c 

C_DEPS += \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctions.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_boolean_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_braycurtis_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_canberra_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_chebyshev_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cityblock_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_correlation_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cosine_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_dice_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_euclidean_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_hamming_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jaccard_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jensenshannon_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_kulsinski_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_minkowski_distance_f32.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_rogerstanimoto_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_russellrao_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalmichener_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalsneath_distance.d \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_yule_distance.d 

OBJS += \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctions.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_boolean_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_braycurtis_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_canberra_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_chebyshev_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cityblock_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_correlation_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cosine_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_dice_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_euclidean_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_hamming_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jaccard_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jensenshannon_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_kulsinski_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_minkowski_distance_f32.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_rogerstanimoto_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_russellrao_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalmichener_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalsneath_distance.o \
./Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_yule_distance.o 


# Each subdirectory must supply rules for building sources it contributes
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctions.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctions.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctions.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_boolean_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_boolean_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_boolean_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_braycurtis_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_braycurtis_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_braycurtis_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_canberra_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_canberra_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_canberra_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_chebyshev_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_chebyshev_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_chebyshev_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cityblock_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cityblock_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cityblock_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_correlation_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_correlation_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_correlation_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cosine_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cosine_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_cosine_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_dice_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_dice_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_dice_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_euclidean_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_euclidean_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_euclidean_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_hamming_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_hamming_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_hamming_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jaccard_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jaccard_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jaccard_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jensenshannon_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jensenshannon_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_jensenshannon_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_kulsinski_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_kulsinski_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_kulsinski_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_minkowski_distance_f32.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_minkowski_distance_f32.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_minkowski_distance_f32.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_rogerstanimoto_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_rogerstanimoto_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_rogerstanimoto_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_russellrao_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_russellrao_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_russellrao_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalmichener_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalmichener_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalmichener_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalsneath_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalsneath_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_sokalsneath_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_yule_distance.o: ../Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_yule_distance.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/CMSIS/DSP/Source/DistanceFunctions/arm_yule_distance.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

