################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/blockio.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/buffer.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/core.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/dir.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/format.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imap.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapextern.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapinline.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inode.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inodedata.c \
../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/volume.c 

C_DEPS += \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/blockio.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/buffer.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/core.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/dir.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/format.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imap.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapextern.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapinline.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inode.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inodedata.d \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/volume.d 

OBJS += \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/blockio.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/buffer.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/core.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/dir.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/format.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imap.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapextern.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapinline.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inode.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inodedata.o \
./Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/volume.o 


# Each subdirectory must supply rules for building sources it contributes
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/blockio.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/blockio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/blockio.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/buffer.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/buffer.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/buffer.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/core.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/core.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/core.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/dir.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/dir.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/dir.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/format.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/format.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/format.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imap.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imap.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imap.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapextern.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapextern.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapextern.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapinline.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapinline.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/imapinline.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inode.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inode.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inode.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inodedata.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inodedata.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/inodedata.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/volume.o: ../Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/volume.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=c11 -g -DSTM32F746xx -c -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src/tensorflow/tensorflow/lite/kernels/internal/reference" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Inc" -I"C:/Users/sm5py/STM32CubeIDE/workspace_1.5.0/stm32f746g_base/Src" -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/BSP/STM32746G-Discovery -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../TinyEngine/include -Ofast -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/ViT_00/libs/freertos/FreeRTOS-Plus/Source/Reliance-Edge/core/driver/volume.d" -MT"$@"  -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

