name: Code Quality Test
on: push

jobs:
  code-gen-test:
    runs-on: xps-runner
    strategy:
      fail-fast: false
      matrix:
        target: [detection_fpn, vww]
    name: Detection FPN
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install tinyengine
        run: |
          python setup.py install
      - name: Generate code for detection
        run: |
          PYTHONPATH=${PYTHONPATH}:$(pwd) python examples/${{ matrix.target }}.py
          unzip tests/examples/assets/${{ matrix.target }}/codegen.zip -d tests/examples/assets/${{ matrix.target }}/
      - id: diff-person-detection
        run: |
          diff -r codegen/ tests/examples/assets/${{ matrix.target }}/codegen/
      - uses: nick-fields/assert-action@v1
        with:
          expected: ''
          actual: ${{ steps.diff-person-detection.outputs.value }}
      - name: clean up
        run: |
          rm -rf codegen
